<a href="https://colab.research.google.com/github/Aingon14/BSC_DPDM23/blob/main/Frequent_Patterns_(Association_Rules).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [120]:
import pandas as pd
import os

In [121]:
from google.colab import drive
drive.mount('/content/drive')
path = '/content/drive/My Drive/bsc_dpdm23_data'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [122]:
data = pd.read_csv(os.path.join(path,'/content/drive/MyDrive/BSC_DPDM23/reduced_marketbasket.csv'),encoding='latin-1')

In [123]:
data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/09/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/09/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/09/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/09/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/09/2011 12:50,4.95,12680.0,France

##quiz : ข้อมูลมาจากกี่ประเทศ

In [124]:
len(set(data['Country']))

38

In [125]:
set(data['Country'])

{'Australia',
 'Austria',
 'Bahrain',
 'Belgium',
 'Brazil',
 'Canada',
 'Channel Islands',
 'Cyprus',
 'Czech Republic',
 'Denmark',
 'EIRE',
 'European Community',
 'Finland',
 'France',
 'Germany',
 'Greece',
 'Hong Kong',
 'Iceland',
 'Israel',
 'Italy',
 'Japan',
 'Lebanon',
 'Lithuania',
 'Malta',
 'Netherlands',
 'Norway',
 'Poland',
 'Portugal',
 'RSA',
 'Saudi Arabia',
 'Singapore',
 'Spain',
 'Sweden',
 'Switzerland',
 'USA',
 'United Arab Emirates',
 'United Kingdom',
 'Unspecified'}

# แปลง data ให้อยู่ในรูปแบบ Transaction data ด้วย groupby.apply(list)

In [126]:
data.groupby('InvoiceNo')['StockCode'].apply(list)

InvoiceNo
536365     [85123A, 71053, 84406B, 84029G, 84029E, 22752,...
536366                                        [22633, 22632]
536367     [84879, 22745, 22748, 22749, 22310, 84969, 226...
536368                          [22960, 22913, 22912, 22914]
536369                                               [21756]
                                 ...
C581484                                              [23843]
C581490                                       [22178, 23144]
C581499                                                  [M]
C581568                                              [21258]
C581569                                       [84978, 20979]
Name: StockCode, Length: 25900, dtype: object

In [127]:
transactions = data.groupby('InvoiceNo')['StockCode'].apply(list)

## Association Rules

In [11]:
!pip install apyori

Requirement already satisfied: apyori in /usr/local/lib/python3.10/dist-packages (1.1.2)

In [12]:
from apyori import apriori

In [13]:
list(apriori(transactions,min_support= 0.065))   #คนที่ซื้อของซ้ำๆกัน

[RelationRecord(items=frozenset({'22423'}), support=0.08386100386100385, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'22423'}), confidence=0.08386100386100385, lift=1.0)]),
 RelationRecord(items=frozenset({'47566'}), support=0.06586872586872587, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'47566'}), confidence=0.06586872586872587, lift=1.0)]),
 RelationRecord(items=frozenset({'85099B'}), support=0.08243243243243244, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'85099B'}), confidence=0.08243243243243244, lift=1.0)]),
 RelationRecord(items=frozenset({'85123A'}), support=0.08671814671814672, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'85123A'}), confidence=0.08671814671814672, lift=1.0)])]

In [14]:
frequentItemsets = list(apriori(transactions,min_support = 0.065))
frequentItemsets

[RelationRecord(items=frozenset({'22423'}), support=0.08386100386100385, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'22423'}), confidence=0.08386100386100385, lift=1.0)]),
 RelationRecord(items=frozenset({'47566'}), support=0.06586872586872587, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'47566'}), confidence=0.06586872586872587, lift=1.0)]),
 RelationRecord(items=frozenset({'85099B'}), support=0.08243243243243244, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'85099B'}), confidence=0.08243243243243244, lift=1.0)]),
 RelationRecord(items=frozenset({'85123A'}), support=0.08671814671814672, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'85123A'}), confidence=0.08671814671814672, lift=1.0)])]

In [15]:
len(frequentItemsets)

4

In [16]:
frequentItemsets[0]

RelationRecord(items=frozenset({'22423'}), support=0.08386100386100385, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'22423'}), confidence=0.08386100386100385, lift=1.0)])

In [17]:
frequentItemsets[0][0]

frozenset({'22423'})

In [18]:
dir(frequentItemsets[0][0])

['__and__',
 '__class__',
 '__class_getitem__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__ne__',
 '__new__',
 '__or__',
 '__rand__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__ror__',
 '__rsub__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__xor__',
 'copy',
 'difference',
 'intersection',
 'isdisjoint',
 'issubset',
 'issuperset',
 'symmetric_difference',
 'union']

In [19]:
frequentItemsets[0][0].__len__()

1

In [20]:
min_sup = 0.03

frequentItemsets = list(apriori(transactions,min_support = min_sup))
for i in frequentItemsets:
    if i[0].__len__()>1:
        print('yes')
        print(i)

yes
RelationRecord(items=frozenset({'85099B', '22386'}), support=0.03216216216216216, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'85099B', '22386'}), confidence=0.03216216216216216, lift=1.0), OrderedStatistic(items_base=frozenset({'22386'}), items_add=frozenset({'85099B'}), confidence=0.6766856214459789, lift=8.20897311262335), OrderedStatistic(items_base=frozenset({'85099B'}), items_add=frozenset({'22386'}), confidence=0.39016393442622943, lift=8.20897311262335)])
yes
RelationRecord(items=frozenset({'22697', '22699'}), support=0.03027027027027027, ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'22697', '22699'}), confidence=0.03027027027027027, lift=1.0), OrderedStatistic(items_base=frozenset({'22697'}), items_add=frozenset({'22699'}), confidence=0.7417218543046358, lift=17.1523178807947), OrderedStatistic(items_base=frozenset({'22699'}), items_add=frozenset({'22697'}), confidence=0.7, lift=17.1523178807947)])

RelationRecord(items=frozenset({'22386', '85099B'}),

support=0.03216216216216216,

ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'22386', '85099B'}), confidence=0.03216216216216216, lift=1.0),

OrderedStatistic(items_base=frozenset({'22386'}), items_add=frozenset({'85099B'}), confidence=0.6766856214459789, lift=8.20897311262335),

OrderedStatistic(items_base=frozenset({'85099B'}), items_add=frozenset({'22386'}), confidence=0.39016393442622943, lift=8.20897311262335)])

In [21]:
set(data[(data['StockCode']=='22386') | (data['StockCode']=='85099B') | (data['StockCode']=='22699') | (data['StockCode']=='22697') ]['Description'])

{'GREEN REGENCY TEACUP AND SAUCER',
 'JUMBO BAG PINK POLKADOT',
 'JUMBO BAG RED RETROSPOT',
 'ROSES REGENCY TEACUP AND SAUCER '}

RelationRecord(items=frozenset({'22699', '22697'}), support=0.03027027027027027,

ordered_statistics=[OrderedStatistic(items_base=frozenset(), items_add=frozenset({'22699', '22697'}), confidence=0.03027027027027027, lift=1.0),

OrderedStatistic(items_base=frozenset({'22697'}), items_add=frozenset({'22699'}), confidence=0.7417218543046358, lift=17.1523178807947),

OrderedStatistic(items_base=frozenset({'22699'}), items_add=frozenset({'22697'}), confidence=0.7, lift=17.1523178807947)])

#Quiz 22386 และ 85099B คือสินค้าอะไร

In [53]:
# 22386, 85099B คือสินค้อะไร
set(data[data['StockCode']=='22386']['Description'])

{'JUMBO BAG PINK POLKADOT'}

In [54]:
set(data[data['StockCode']=='85099B']['Description'])

{'JUMBO BAG RED RETROSPOT'}

In [24]:
set(data[(data['StockCode']=='22699') | (data['StockCode']=='22697')]['InvoiceNo'])

{'568060',
 '546683',
 '557064',
 '575490',
 '550470',
 '546442',
 '576063',
 '580673',
 '568676',
 '543188',
 '571797',
 'C567358',
 '562711',
 '566094',
 '543019',
 '565917',
 '555477',
 '556459',
 '550953',
 '562420',
 '547580',
 '553535',
 '558923',
 '580053',
 '573397',
 '574076',
 'C550648',
 '565234',
 '578936',
 '570720',
 '564541',
 '570677',
 '562033',
 '557502',
 '548648',
 '579512',
 '540464',
 '564972',
 '553210',
 '544089',
 '561095',
 '547249',
 '555400',
 '557262',
 '548373',
 '549016',
 '552308',
 '577498',
 '554054',
 '575739',
 '540005',
 '560976',
 '554643',
 '536946',
 '559491',
 '567293',
 '574298',
 '558103',
 '561051',
 '548919',
 '560246',
 '569834',
 'C552016',
 '559295',
 '547826',
 '550915',
 '549730',
 '549425',
 '537022',
 '543036',
 '544434',
 '563534',
 '565916',
 '570270',
 '536876',
 'C545449',
 '551995',
 '542102',
 'C558255',
 '562219',
 '544681',
 '536980',
 '560634',
 '552816',
 '580665',
 '560895',
 '541870',
 '550205',
 '557431',
 '542344',
 '577039',
 '576202',
 '544208',
 '538148',
 '541008',
 'C574507',
 '564820',
 '545176',
 '562377',
 '552715',
 '574561',
 '540907',
 '550914',
 '554974',
 'C577388',
 '561070',
 '544456',
 '553387',
 '549524',
 '566624',
 '545036',
 '575947',
 '548163',
 '581023',
 '565748',
 '560580',
 'C545724',
 '540777',
 '567368',
 '575515',
 '553942',
 '563909',
 '567873',
 '548192',
 '550968',
 'C545444',
 '539564',
 '555722',
 'C556268',
 '565424',
 '565994',
 '541421',
 '541866',
 '559055',
 '548159',
 '559923',
 '553661',
 '557350',
 '580612',
 '577258',
 '564837',
 '579471',
 '544660',
 '573266',
 '563613',
 '545445',
 '549852',
 '570388',
 '543097',
 '548983',
 '555488',
 '566871',
 '570597',
 '571241',
 'C550664',
 '578817',
 '576672',
 '571937',
 '548260',
 '558119',
 '547248',
 '549124',
 '575866',
 '553182',
 '562607',
 '549595',
 '544055',
 '551057',
 '558120',
 '557301',
 '537470',
 '549592',
 '547397',
 '555854',
 '552563',
 '544664',
 '538524',
 '558904',
 'C572410',
 '571931',
 '539736',
 'C574548',
 '560590',
 '575063',
 '579938',
 '537042',
 '578833',
 '550307',
 '550503',
 '579267',
 '555147',
 '560790',
 '554935',
 'C558434',
 '546892',
 '570258',
 '562273',
 '555870',
 '563166',
 '548734',
 '559112',
 '559489',
 '541423',
 '551334',
 '570465',
 '537237',
 '540664',
 '541949',
 '579503',
 '566537',
 '540662',
 '556767',
 '575939',
 '579539',
 '572549',
 '536627',
 '547360',
 '566583',
 '550638',
 '544301',
 '561637',
 '538903',
 '559052',
 '565847',
 '542543',
 '557859',
 '566477',
 'C569114',
 '551088',
 '560398',
 '565117',
 '552734',
 '550302',
 '545020',
 '580774',
 '562573',
 '577316',
 '579196',
 '578949',
 '575185',
 '537823',
 '553899',
 '540839',
 '548739',
 '578149',
 '576618',
 'C567955',
 'C543837',
 '579777',
 '561651',
 '537435',
 '539217',
 '580669',
 'C562953',
 '572229',
 '562427',
 '541999',
 '554694',
 '553191',
 '563569',
 '550213',
 '542629',
 '560780',
 '548974',
 '566559',
 '550186',
 '552664',
 '567140',
 '565151',
 '552302',
 '556082',
 '564835',
 '549435',
 '546992',
 '557034',
 '544186',
 '553385',
 '581472',
 '542664',
 '562282',
 '552557',
 '545340',
 '542619',
 '559357',
 '567128',
 '553870',
 '540259',
 '559679',
 '576388',
 '537638',
 'C566084',
 '563477',
 '545320',
 '560209',
 '561702',
 '549305',
 '551531',
 '542583',
 '540499',
 '550210',
 '543602',
 '541220',
 '558089',
 '565150',
 '552956',
 '540539',
 '560773',
 '547846',
 '566257',
 '546896',
 '569496',
 '544565',
 '544075',
 '542632',
 '569493',
 '541110',
 '555594',
 '536804',
 '568333',
 '553035',
 '556073',
 '558240',
 '551564',
 '540646',
 '572550',
 '564300',
 '536624',
 '542999',
 '544067',
 'C564964',
 '550265',
 '569568',
 '541219',
 '553462',
 '558774',
 '573388',
 '543370',
 '578031',
 '571745',
 '536865',
 '561371',
 '564091',
 '550201',
 '566617',
 '541709',
 '555150',
 '564301',
 '548733',
 '557117',
 '571546',
 '581495',
 '554514',
 '566396',
 '573576',
 '579012',
 '566981',
 '536856',
 'C545525',
 'C537834',
 '553146',
 'C566758',
 '571560',
 '558259',
 '561217',
 '570701',
 '553013',
 '540992',
 '538660',
 '552270',
 '560604',
 '546306',
 '567905',
 '559525',
 '568792',
 '546498',
 '543973',
 '569918',
 '554557',
 '569367',
 '575932',
 '579694',
 'C555409',
 '560906',
 'C545438',
 '548768',
 '556016',
 '570713',
 '566985',
 '540418',
 '557621',
 '575176',
 '576181',
 '539593',
 '555327',
 '567631',
 '543565',
 '544778',
 '565675',
 '545032',
 '576339',
 'C550808',
 '576837',
 '578065',
 '547400',
 '545022',
 '541810',
 'C544665',
 '571058',
 '536623',
 '544206',
 '575846',
 'C562921',
 '537645',
 '547712',
 '536592',
 '548860',
 '550314',
 '576690',
 '567671',
 '554124',
 '562843',
 '547250',
 '548726',
 '567639',
 '545411',
 '562374',
 '556415',
 '552678',
 '554028',
 '544913',
 '561798',
 '575477',
 'C565848',
 '555106',
 'C545456',
 '554040',
 '549999',
 '565849',
 '546136',
 '575206',
 '561891',
 '573125',
 '545464',
 '537955',
 '577594',
 '562950',
 '556917',
 '537335',
 '553612',
 '536524',
 '555510',
 '544421',
 '557735',
 '547107',
 '552247',
 '539594',
 '545759',
 '551343',
 '562157',
 '565862',
 '543546',
 'C538059',
 '550986',
 '574707',
 '562102',
 '560772',
 '555851',
 '562553',
 '550251',
 '564552',
 '565231',
 '542590',
 '552687',
 '554337',
 '545333',
 '571034',
 '548522',
 '547063',
 'C556793',
 '567336',
 '542691',
 '567157',
 '539738',
 '551550',
 '573330',
 '548516',
 '543985',
 '549951',
 '559886',
 'C552698',
 '550987',
 '549261',
 '545721',
 '571714',
 '566581',
 '552843',
 '581217',
 '552493',
 '555848',
 '542622',
 '553766',
 '556501',
 '575221',
 '560473',
 '559173',
 '561820',
 '544657',
 '557973',
 '569577',
 '540026',
 'C545828',
 '557259',
 '568193',
 '544887',
 'C556880',
 '545426',
 '552449',
 '539436',
 '543732',
 '567886',
 '546096',
 '543923',
 '537666',
 '546158',
 '550989',
 '581492',
 '571257',
 '546927',
 '550438',
 '568134',
 '570257',
 '565223',
 '544095',
 '564755',
 '559494',
 '563614',
 '564817',
 '541783',
 '569544',
 '551387',
 '566124',
 '572751',
 '546752',
 '547386',
 '538153',
 '543660',
 '543107',
 '551657',
 '553566',
 '560357',
 '563896',
 '559938',
 '572655',
 '570834',
 '557672',
 '562849',
 '543629',
 '562955',
 '565331',
 '540154',
 '569888',
 '572212',
 '552665',
 'C551511',
 '570488',
 '577078',
 '553869',
 '554013',
 '575703',
 '566400',
 '556813',
 'C560588',
 '545526',
 '537378',
 '543754',
 '544749',
 '543532',
 '566060',
 '547967',
 '579751',
 '558683',
 '552149',
 'C541822',
 '576246',
 '552232',
 '554026',
 '564199',
 '570428',
 '545912',
 '568310',
 '555278',
 '564306',
 '549525',
 '570227',
 '563549',
 '561329',
 '576616',
 '546888',
 '563561',
 '558116',
 'C577752',
 '564191',
 '565838',
 '543201',
 '559942',
 '566790',
 '541130',
 '563076',
 '555871',
 '551286',
 '543022',
 '544768',
 '570514',
 'C542263',
 '547498',
 '545945',
 '553542',
 '543099',
 '578993',
 '551339',
 'C555254',
 '575930',
 '554483',
 '552694',
 '543826',
 '544837',
 '572552',
 '545154',
 '562429',
 '546891',
 '565724',
 '575620',
 '566731',
 '558565',
 '539450',
 '545428',
 '545377',
 '556083',
 '556503',
 '539741',
 '540364',
 '578331',
 '545474',
 '551014',
 '544812',
 '539609',
 '578044',
 '581170',
 '577319',
 '566091',
 '539752',
 '542600',
 '565919',
 '552857',
 '554560',
 '569545',
 '581006',
 '560291',
 '573822',
 '573320',
 '572066',
 '545690',
 '538951',
 '537830',
 '572082',
 '545895',
 '544824',
 '574334',
 '540981',
 'C546865',
 '541530',
 '550978',
 '551997',
 '545343',
 '571061',
 '541424',
 '571550',
 '546884',
 '543013',
 '577500',
 '548987',
 '556577',
 '565781',
 'C546125',
 '566446',
 '566326',
 '536523',
 '547788',
 '551944',
 '570824',
 '565289',
 'C556644',
 '563023',
 '540371',
 'C542912',
 '545014',
 '580983',
 '545063',
 '569202',
 '581345',
 '543909',
 '566577',
 '580730',
 '547042',
 '573338',
 '570459',
 '543106',
 '575875',
 '557500',
 '544394',
 '552663',
 '556264',
 'C539071',
 '563505',
 '562202',
 '580098',
 '556434',
 '542729',
 '571283',
 '565120',
 '557616',
 '558068',
 '564432',
 '548893',
 '547547',
 '577355',
 '541960',
 '538880',
 '564723',
 '553709',
 '555486',
 '559510',
 '551058',
 '547385',
 '553541',
 '543626',
 '577618',
 '546669',
 '551953',
 '537887',
 '548212',
 '567663',
 '544677',
 '547936',
 '566221',
 'C567885',
 '558918',
 'C566167',
 '573070',
 'C569911',
 'C564854',
 '570086',
 '571441',
 '554329',
 '552710',
 '576644',
 '537313',
 '539492',
 '541280',
 '545543',
 '546562',
 '542779',
 '564975',
 '543486',
 '545460',
 '545696',
 'C554330',
 '558066',
 '557211',
 '568346',
 '552533',
 'C548355',
 '544668',
 '544574',
 '557642',
 '577029',
 '578354',
 '568654',
 '539437',
 'C562375',
 '566255',
 '547493',
 '541584',
 '541592',
 '545701',
 '551775',
 '553578',
 '572028',
 '576329',
 '546212',
 '557645',
 'C562119',
 '579508',
 '568781',
 '560504',
 '554714',
 '537534',
 '562365',
 '553546',
 '542862',
 '571305',
 '541129',
 '580173',
 '539739',
 '576899',
 '554039',
 '579445',
 '572854',
 '558073',
 '555743',
 '558348',
 'C553479',
 '545078',
 '540848',
 '552662',
 '551005',
 '552196',
 '564974',
 '546688',
 '556323',
 '547387',
 '548210',
 '577400',
 '556284',
 '555630',
 '558443',
 '575138',
 '546315',
 '553671',
 '558873',
 '564857',
 '565396',
 '543277',
 '566976',
 '555524',
 '559930',
 '558702',
 '566988',
 '544779',
 '547841',
 '568955',
 '577020',
 '571216',
 '566482',
 '539434',
 '549056',
 '543485',
 '565519',
 '539442',
 '564057',
 '566170',
 '549295',
 '577531',
 '573580',
 '554415',
 '541497',
 '577518',
 '565841',
 '554326',
 '555574',
 '576651',
 '568553',
 '580367',
 '541811',
 '544569',
 '546367',
 '577358',
 '564838',
 '550437',
 '548808',
 '550499',
 '537385',
 '566193',
 '544081',
 '581122',
 '553489',
 '553607',
 '550333',
 '552257',
 '568651',
 '549120',
 '580526',
 '551171',
 '564184',
 '551340',
 '570187',
 '542115',
 '564714',
 '547206',
 '563931',
 '560826',
 '566290',
 '569246',
 '572274',
 '550468',
 '568988',
 '568908',
 '542647',
 '543399',
 '578273',
 '559557',
 '576051',
 '574950',
 '578344',
 '556636',
 'C579945',
 '579885',
 '580727',
 '539742',
 '579297',
 '566572',
 '548194',
 '541695',
 '557494',
 '548191',
 '580501',
 '559878',
 '551160',
 '562113',
 '561714',
 '552540',
 '555695',
 '565286',
 '555836',
 '581433',
 '546760',
 '556821',
 '566395',
 '550025',
 '556783',
 'C562147',
 '556237',
 '548718',
 '567670',
 '555277',
 '555158',
 '544339',
 '546545',
 '561125',
 '569555',
 '551414',
 '536862',
 'C541693',
 '552642',
 '554813',
 '540372',
 '544940',
 '570688',
 'C551465',
 '568057',
 '562534',
 '565056',
 '567922',
 '554959',
 '550899',
 '560777',
 '551825',
 '561933',
 '565840',
 '573553',
 '545719',
 'C549840',
 '550458',
 '559693',
 'C560560',
 '574731',
 '550958',
 '577610',
 '566600',
 '575946',
 '555522',
 '549909',
 '576381',
 '558372',
 '551860',
 '575484',
 '567341',
 '547830',
 '538071',
 '553543',
 '572758',
 '545475',
 '578016',
 '564092',
 '577597',
 '568655',
 '549052',
 '544205',
 '561926',
 '581059',
 '573020',
 '553891',
 'C559949',
 '551850',
 '555499',
 '566788',
 '570872',
 '542527',
 '564056',
 '539465',
 ...}

In [25]:
data[data['InvoiceNo']=='562950']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
297488,562950,22752,SET 7 BABUSHKA NESTING BOXES,2,08/11/2011 09:56,8.50,15608.0,United Kingdom
297489,562950,22755,SMALL PURPLE BABUSHKA NOTEBOOK,12,08/11/2011 09:56,0.85,15608.0,United Kingdom
297490,562950,22753,SMALL YELLOW BABUSHKA NOTEBOOK,12,08/11/2011 09:56,0.85,15608.0,United Kingdom
297491,562950,22754,SMALL RED BABUSHKA NOTEBOOK,12,08/11/2011 09:56,0.85,15608.0,United Kingdom
297492,562950,22757,LARGE RED BABUSHKA NOTEBOOK,12,08/11/2011 09:56,1.25,15608.0,United Kingdom
297493,562950,22758,LARGE PURPLE BABUSHKA NOTEBOOK,12,08/11/2011 09:56,1.25,15608.0,United Kingdom
297494,562950,22756,LARGE YELLOW BABUSHKA NOTEBOOK,12,08/11/2011 09:56,1.25,15608.0,United Kingdom
297495,562950,23310,BUBBLEGUM RING ASSORTED,36,08/11/2011 09:56,0.42,15608.0,United Kingdom
297496,562950,23280,FOLDING BUTTERFLY MIRROR HOT PINK,12,08/11/2011 09:56,0.83,15608.0,United Kingdom
297497,562950,22383,LUNCH BAG SUKI DESIGN,10,08/11/2011 09:56,1.65,15608.0,United Kingdom
297498,562950,22492,MINI PAINT SET VINTAGE,36,08/11/2011 09:56,0.65,15608.0,United Kingdom
297499,562950,71459,HANGING JAM JAR T-LIGHT HOLDER,12,08/11/2011 09:56,0.85,15608.0,United Kingdom
297500,562950,84945,MULTI COLOUR SILVER T-LIGHT HOLDER,12,08/11/2011 09:56,0.85,15608.0,United Kingdom
297501,562950,21175,GIN + TONIC DIET METAL SIGN,12,08/11/2011 09:56,2.55,15608.0,United Kingdom
297502,562950,23164,REGENCY CAKE SLICE,4,08/11/2011 09:56,4.95,15608.0,United Kingdom
297503,562950,23245,SET OF 3 REGENCY CAKE TINS,4,08/11/2011 09:56,4.95,15608.0,United Kingdom
297504,562950,23171,REGENCY TEA PLATE GREEN,12,08/11/2011 09:56,1.65,15608.0,United Kingdom
297505,562950,22697,GREEN REGENCY TEACUP AND SAUCER,6,08/11/2011 09:56,2.95,15608.0,United Kingdom

# HW1 หา Frequent Item Set และ Association Rules

* ของช่วงเวลา Chrhistmas & New Year (1 Dec - 31 Dec)
* ของประเทศในทวีป Europe
* ของช่วงเวลาตรุษจีน ในทวีป Asia (15 Jan - 15 Feb)
* ของช่วงเวลา Chrhistmas & New Year ในทวีป Europe (1 Dec - 31 Dec)
* ของวันวาเลนไทน์
* โดยจัดกลุ่มตามประเทศ + เดือน (groupby ประเทศกับเดือน)

In [91]:
data['InvoiceDate'][0]

'12/01/2010 08:26'

In [92]:
data['InvoiceDate'][0].split()[0] #ตัด

'12/01/2010'

In [93]:
date =[]
for i in range(len(data['InvoiceDate'])):
  x = data['InvoiceDate'][i].split()[0]
  date.append(x)

In [95]:
date[0].split('/')

['12', '01', '2010']

In [111]:
#แยกวัน เดือน ปี ออกจากกัน
day =[]
month =[]
year =[]
for i in range(len(data['InvoiceDate'])):
  m = date[i].split('/')[0]
  d = date[i].split('/')[1]
  y = date[i].split('/')[2]
  month.append(m)
  day.append(d)
  year.append(y)

In [112]:
data_test=data

In [113]:
data_test['date']=date
data_test['day']=day
data_test['month']=month
data_test['year']=year

In [114]:
#แปลงวัน
x=[]
for i in range(1,32):
  x.append(i)
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]

In [115]:
data_day=data_test.replace(['01', '02', '03', '04', '05', '06', '07', '08', '09', '10','11',
                                      '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '30', '31'],x)   #แทนที่วันจาก str

In [116]:
data_day

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,date,day,month,year
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26,2.55,17850.0,United Kingdom,12/01/2010,1,12,2010
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,1,12,2010
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26,2.75,17850.0,United Kingdom,12/01/2010,1,12,2010
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,1,12,2010
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,1,12,2010
...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/09/2011 12:50,0.85,12680.0,France,12/09/2011,9,12,2011
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/09/2011 12:50,2.10,12680.0,France,12/09/2011,9,12,2011
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/09/2011 12:50,4.15,12680.0,France,12/09/2011,9,12,2011
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/09/2011 12:50,4.15,12680.0,France,12/09/2011,9,12,2011
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/09/2011 12:50,4.95,12680.0,France,12/09/2011,9,12,2011

In [117]:
set(data_test['month'])  #ข้อมูลมีทั้ง str และแบบตัวเลข

{'01',
 '02',
 '03',
 '04',
 '05',
 '06',
 '07',
 '08',
 '09',
 '1',
 '10',
 '11',
 '12',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9'}

In [118]:
data_test1=data_test.replace(to_replace=["1", "2",'3','4','5','6','7','8','9'],value=[1,2,3,4,5,6,7,8,9])
data_test1

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,date,day,month,year
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26,2.55,17850.0,United Kingdom,12/01/2010,01,12,2010
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,01,12,2010
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26,2.75,17850.0,United Kingdom,12/01/2010,01,12,2010
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,01,12,2010
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,01,12,2010
...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/09/2011 12:50,0.85,12680.0,France,12/09/2011,09,12,2011
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/09/2011 12:50,2.10,12680.0,France,12/09/2011,09,12,2011
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/09/2011 12:50,4.15,12680.0,France,12/09/2011,09,12,2011
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/09/2011 12:50,4.15,12680.0,France,12/09/2011,09,12,2011
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/09/2011 12:50,4.95,12680.0,France,12/09/2011,09,12,2011

In [119]:
data_test.isnull().any()

InvoiceNo      False
StockCode      False
Description     True
Quantity       False
InvoiceDate    False
UnitPrice      False
CustomerID      True
Country        False
date           False
day            False
month          False
year           False
dtype: bool

In [104]:
data_test

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,date,day,month,year
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/01/2010 08:26,2.55,17850.0,United Kingdom,12/01/2010,01,12,2010
1,536365,71053,WHITE METAL LANTERN,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,01,12,2010
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/01/2010 08:26,2.75,17850.0,United Kingdom,12/01/2010,01,12,2010
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,01,12,2010
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/01/2010 08:26,3.39,17850.0,United Kingdom,12/01/2010,01,12,2010
...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/09/2011 12:50,0.85,12680.0,France,12/09/2011,09,12,2011
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/09/2011 12:50,2.10,12680.0,France,12/09/2011,09,12,2011
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/09/2011 12:50,4.15,12680.0,France,12/09/2011,09,12,2011
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/09/2011 12:50,4.15,12680.0,France,12/09/2011,09,12,2011
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/09/2011 12:50,4.95,12680.0,France,12/09/2011,09,12,2011

## ข้อ1

In [105]:
data_C_N= data_test[data_test['month']==12]
data_C_N

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country, date, day, month, year]
Index: []

In [106]:
!pip install apyori
from apyori import apriori

Requirement already satisfied: apyori in /usr/local/lib/python3.10/dist-packages (1.1.2)

In [107]:
transactions_C_N = data_C_N.groupby('InvoiceNo')['StockCode'].apply(list)
transactions_C_N

<ipython-input-107-e686f91dd3a2>:1: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  transactions_C_N = data_C_N.groupby('InvoiceNo')['StockCode'].apply(list)

Series([], Name: StockCode, dtype: object)

In [43]:
#frequentItemsets = list(apriori(transactions_C_N,min_support = 0.05))
#frequentItemsets

In [108]:
frequentItemsets_C_N = list(apriori(transactions_C_N,min_support = 0.04))
for i in frequentItemsets_C_N:
    if i[0].__len__()>1:
        print('yes')
        print(i)

## group by  ข้อ1

In [109]:
transactions_C_N = data_C_N.groupby(['Country', 'month'])['StockCode'].apply(list)

<ipython-input-109-0dc4b228102a>:1: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  transactions_C_N = data_C_N.groupby(['Country', 'month'])['StockCode'].apply(list)

In [110]:
transactions_C_N

Series([], Name: StockCode, dtype: object)

In [1]:
frequentItemsets_C_N = list(apriori(transactions_C_N,min_support = 0.03))
for i in frequentItemsets_C_N:
    if i[0].__len__()>1:
        print('yes')
        print(i)

NameError: name 'apriori' is not defined

In [128]:
import datetime

In [129]:
data['InvoiceDate']

0         12/01/2010 08:26
1         12/01/2010 08:26
2         12/01/2010 08:26
3         12/01/2010 08:26
4         12/01/2010 08:26
                ...
541904    12/09/2011 12:50
541905    12/09/2011 12:50
541906    12/09/2011 12:50
541907    12/09/2011 12:50
541908    12/09/2011 12:50
Name: InvoiceDate, Length: 541909, dtype: object

In [132]:
data['InvoiceDate']=pd.to_datetime(data.InvoiceDate, format='%m/%d/%Y')

ValueError: unconverted data remains:  08:26

In [130]:
data['Date'] = data['InvoiceDate'].dt.date

AttributeError: Can only use .dt accessor with datetimelike values